/* Details a generic Specification object.

The object is in reality a map from a string parameter to a Generator object.
An object that the Specification describes should be generated by invoking each
Generator object as needed. For example, suppose we had:

  struct Foo {
    int a;
    string b;
  };

and a Foo spec. Using that spec, a Foo could be created:

  foo.a = spec["a"]->generateInt(rng);
  foo.b = spec["b"]->generateString(rng);
*/
#pragma once

#ifndef SWIG
#include <map>
#include <string>
#endif // SWIG
#include <Generator.h>

namespace slug {

namespace spec {

typedef std::map<std::string, Generator*> Specification;

} // namespace spec

} // namespace slug
