language: python
python: 2.7

env:
    - TOX_ENV=py26-twlatest
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py26-tw140
    - TOX_ENV=py26-tw132
    - TOX_ENV=py26-tw131
    - TOX_ENV=py26-tw130
    - TOX_ENV=py26-tw123
    - TOX_ENV=py26-tw122
    - TOX_ENV=py26-tw121
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw140
    - TOX_ENV=py27-tw132
    - TOX_ENV=py27-tw131
    - TOX_ENV=py27-tw130
    - TOX_ENV=py27-tw123
    - TOX_ENV=py27-tw122
    - TOX_ENV=py27-tw121
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pypy-tw140
    - TOX_ENV=pypy-tw132
    - TOX_ENV=pypy-tw131
    - TOX_ENV=pypy-tw130
    - TOX_ENV=pypy-tw123
    - TOX_ENV=pypy-tw122
    - TOX_ENV=pypy-tw121
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pyflakes

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
