# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: include/ncs/proto/SimData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='include/ncs/proto/SimData.proto',
  package='',
  serialized_pb='\n\x1finclude/ncs/proto/SimData.proto\"\x17\n\x07SimData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x02')




_SIMDATA = _descriptor.Descriptor(
  name='SimData',
  full_name='SimData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SimData.data', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['SimData'] = _SIMDATA

class SimData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIMDATA

  # @@protoc_insertion_point(class_scope:SimData)


# @@protoc_insertion_point(module_scope)
